version: '3.8'

services:
  todo:
    image: elyrah/todo:latest
    ports:
      - "5000:5000"
    volumes:
      - todo-db:/app/instance
    environment:
      - FLASK_ENV=development

volumes:
  todo-db: